### ISSUE TITLE
Element-wise multiplication: not supported between 'Matrix' and 'Vector' types

### ISSUE THREAD

**Issue by animate1978** [animate1978/spiderwebs#1]
When selecting 'Vertices' or 'Edges' as the 'Method' this error pops up

Traceback (most recent call last):
  File "/home/farishta/blender-2.83.16-linux-x64/2.83/scripts/addons/spiderwebs/add_curve_spiderwebs.py", line 167, in execute
    points = mesh_tools.get_points(obj, amount=obj_amount, method=self.method, apply_modifiers=True, seed=self.seed)
  File "/home/farishta/blender-2.83.16-linux-x64/2.83/scripts/addons/spiderwebs/mesh_tools.py", line 172, in get_points
    return get_random_points_on_edges(mesh, amount, transform_matrix, seed=seed)
  File "/home/farishta/blender-2.83.16-linux-x64/2.83/scripts/addons/spiderwebs/mesh_tools.py", line 69, in get_random_points_on_edges
    points.append(transform_matrix * p)
TypeError: Element-wise multiplication: not supported between 'Matrix' and 'Vector' types

location: <unknown location>:-1

**Comment by animate1978** [comment]
With last commit, this issue was resolved
